spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventservice?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        batch_fetch_style: legacy #dynamic
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.type: trace